site_name: simplechatbot
site_url: https://devincornell.github.io/simplechatbot
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.copy
    - navigation.expand
    - content.code.annotate #
repo_url: https://github.com/devincornell/simplechatbot
repo_name: devincornell/simplechatbot
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true

  - pymdownx.superfences 
